"""create demo tables

Revision ID: a5a68cdb0ac4
Revises: 65e995c575f1
Create Date: 2026-05-24 19:47:57.565825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5a68cdb0ac4'
down_revision: Union[str, Sequence[str], None] = '65e995c575f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('quarter', sa.String(length=6), nullable=False),
    sa.Column('rows_seen', sa.Integer(), nullable=False),
    sa.Column('rows_clean', sa.Integer(), nullable=False),
    sa.Column('rows_rejected', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='faers'
    )
    op.create_table('demo_clean',
    sa.Column('primaryid', sa.BigInteger(), nullable=False),
    sa.Column('caseid', sa.BigInteger(), nullable=False),
    sa.Column('caseversion', sa.Integer(), nullable=False),
    sa.Column('i_f_code', sa.String(length=1), nullable=False),
    sa.Column('event_dt', sa.String(length=8), nullable=True),
    sa.Column('event_dt_precision', sa.String(length=5), nullable=True),
    sa.Column('event_dt_value', sa.Date(), nullable=True),
    sa.Column('mfr_dt', sa.String(length=8), nullable=True),
    sa.Column('mfr_dt_precision', sa.String(length=5), nullable=True),
    sa.Column('mfr_dt_value', sa.Date(), nullable=True),
    sa.Column('init_fda_dt', sa.String(length=8), nullable=True),
    sa.Column('init_fda_dt_precision', sa.String(length=5), nullable=True),
    sa.Column('init_fda_dt_value', sa.Date(), nullable=True),
    sa.Column('fda_dt', sa.String(length=8), nullable=True),
    sa.Column('fda_dt_precision', sa.String(length=5), nullable=True),
    sa.Column('fda_dt_value', sa.Date(), nullable=True),
    sa.Column('rept_dt', sa.String(length=8), nullable=True),
    sa.Column('rept_dt_precision', sa.String(length=5), nullable=True),
    sa.Column('rept_dt_value', sa.Date(), nullable=True),
    sa.Column('rept_cod', sa.String(length=8), nullable=False),
    sa.Column('auth_num', sa.Text(), nullable=True),
    sa.Column('mfr_num', sa.Text(), nullable=True),
    sa.Column('mfr_sndr', sa.Text(), nullable=False),
    sa.Column('lit_ref', sa.Text(), nullable=True),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('age_cod', sa.String(length=3), nullable=True),
    sa.Column('age_grp', sa.String(length=1), nullable=True),
    sa.Column('age_years', sa.Float(), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('e_sub', sa.String(length=1), nullable=False),
    sa.Column('wt', sa.Float(), nullable=True),
    sa.Column('wt_cod', sa.String(length=3), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('to_mfr', sa.String(length=1), nullable=True),
    sa.Column('occp_cod', sa.String(length=2), nullable=True),
    sa.Column('reporter_country', sa.String(length=32), nullable=True),
    sa.Column('occr_country', sa.String(length=32), nullable=True),
    sa.Column('event_dt_suspect_imputed', sa.Boolean(), nullable=False),
    sa.Column('age_group_boundary_mismatch', sa.Boolean(), nullable=False),
    sa.Column('ingest_run_id', sa.UUID(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['faers.ingest_run.id'], ),
    sa.PrimaryKeyConstraint('primaryid'),
    schema='faers'
    )
    op.create_index('ix_demo_clean_caseid', 'demo_clean', ['caseid'], unique=False, schema='faers')
    op.create_index('ix_demo_clean_event_dt_value', 'demo_clean', ['event_dt_value'], unique=False, schema='faers')
    op.create_index('ix_demo_clean_reporter_country', 'demo_clean', ['reporter_country'], unique=False, schema='faers')
    op.create_table('demo_rejected',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('primaryid', sa.BigInteger(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_summary', sa.String(length=64), nullable=False),
    sa.Column('source_line_number', sa.Integer(), nullable=True),
    sa.Column('ingest_run_id', sa.UUID(), nullable=False),
    sa.Column('rejected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['faers.ingest_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='faers'
    )
    op.create_index('ix_demo_rejected_error_summary', 'demo_rejected', ['error_summary'], unique=False, schema='faers')
    op.create_index('ix_demo_rejected_ingest_run', 'demo_rejected', ['ingest_run_id'], unique=False, schema='faers')
    op.create_index('ix_demo_rejected_primaryid', 'demo_rejected', ['primaryid'], unique=False, schema='faers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_demo_rejected_primaryid', table_name='demo_rejected', schema='faers')
    op.drop_index('ix_demo_rejected_ingest_run', table_name='demo_rejected', schema='faers')
    op.drop_index('ix_demo_rejected_error_summary', table_name='demo_rejected', schema='faers')
    op.drop_table('demo_rejected', schema='faers')
    op.drop_index('ix_demo_clean_reporter_country', table_name='demo_clean', schema='faers')
    op.drop_index('ix_demo_clean_event_dt_value', table_name='demo_clean', schema='faers')
    op.drop_index('ix_demo_clean_caseid', table_name='demo_clean', schema='faers')
    op.drop_table('demo_clean', schema='faers')
    op.drop_table('ingest_run', schema='faers')
    # ### end Alembic commands ###
